config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("songs.urls", namespace="songs")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("interactions/", include("interactions.urls", namespace="interactions")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

interactions/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "interactions"

urlpatterns = [
    path("playlists/", views.PlaylistsView.as_view(), name="playlists"),
    path("playlist/<int:pk>/", views.PlaylistView.as_view(), name="playlist"),
]

songs/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "songs"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("releases/", views.ReleasesView.as_view(), name="releases"),
    path("release/<int:pk>/", views.ReleaseView.as_view(), name="release"),
    path("artists/", views.ArtistsView.as_view(), name="artists"),
    path("artist/<int:pk>/", views.ArtistView.as_view(), name="artist"),
    path("like_unlike/<int:pk>/", views.LikeUnlikeSongView.as_view(), name="like_unlike"),
]

interactions/models.py
from django.db import models
from accounts.models import User
from songs.models import Song


class Playlist(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    image = models.ImageField(upload_to="playlists/cover_photo", default="default/icon_default.jpg")
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    songs = models.ManyToManyField(Song)
    created_at = models.DateTimeField(auto_now_add=True)


class Like(models.Model):
    song = models.ForeignKey(Song, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)


class Comment(models.Model):
    song = models.ForeignKey(Song, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment_reply = models.ForeignKey(
        "self",
        related_name="comments_reply",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
    )
    body = models.TextField()
    is_reply = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    is_confirmed = models.BooleanField(default=False)

interactions/forms.py
from django import forms

class AddPlaylistForm(forms.Form):
    name = forms.CharField()
    description = forms.CharField()

interactions/views.py
from django.shortcuts import render
from django.views import View
from .models import Playlist
from songs.models import Song
from .forms import AddPlaylistForm

# Create your views here.
class PlaylistView(View):
    def get(self, request, *args, **kwargs):
        user = request.user
        playlist = Playlist.objects.get(pk=kwargs["pk"], user=user)
        context = {"playlist": playlist}
        return render(request, "interactions/playlist.html", context=context)

    def post(self, request, *args, **kwargs):
        pass


class PlaylistsView(View):
    def get(self, request, *args, **kwargs):
        user = request.user
        playlists = Playlist.objects.filter(user=user).order_by("created_at")
        context = {"playlists": playlists}
        return render(request, "interactions/playlists.html", context=context)

    # def post(self, request, *args, **kwargs):
    #     Playlist.objects.create(user=request.user,)


class AddPlaylistsView(View):
    form_class = AddPlaylistForm

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        songs = Song.objects.all().order_by("created_at")
        context = {"songs": songs, "form": form}
        return render(request, "songs/add_playlist.html", context=context)

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            Playlist.objects.create(
                user=request.user, name=cd["name"], description=cd["description"]
            )

interactions/templates/interactions/playlist.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
	test
{% endblock %}
{% block content %}
<!-- main content -->
<main class="main">
	<div class="container-fluid">
		<div class="row row--grid">
			<!-- breadcrumb -->
			<div class="col-12">
				<ul class="breadcrumb">
					<li class="breadcrumb__item"><a href="index.html">Home</a></li>
					<li class="breadcrumb__item breadcrumb__item--active">playlist</li>
				</ul>
			</div>
			<!-- end breadcrumb -->

			<!-- title -->
			<div class="col-12">
				<div class="main__title main__title--page">
					<h1>{{ playlist.name }}</h1>
				</div>
			</div>
			<!-- end title -->

			<div class="col-12">
				<div class="release">
					<div class="release__content">
						<div class="release__cover">
							<img src="{{ playlist.image.url }}" alt="">
						</div>
						<div class="release__stat">
							<span><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M21.65,2.24a1,1,0,0,0-.8-.23l-13,2A1,1,0,0,0,7,5V15.35A3.45,3.45,0,0,0,5.5,15,3.5,3.5,0,1,0,9,18.5V10.86L20,9.17v4.18A3.45,3.45,0,0,0,18.5,13,3.5,3.5,0,1,0,22,16.5V3A1,1,0,0,0,21.65,2.24ZM5.5,20A1.5,1.5,0,1,1,7,18.5,1.5,1.5,0,0,1,5.5,20Zm13-2A1.5,1.5,0,1,1,20,16.5,1.5,1.5,0,0,1,18.5,18ZM20,7.14,9,8.83v-3L20,4.17Z"/></svg> 10 tracks</span>
							<span><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M20,13.18V11A8,8,0,0,0,4,11v2.18A3,3,0,0,0,2,16v2a3,3,0,0,0,3,3H8a1,1,0,0,0,1-1V14a1,1,0,0,0-1-1H6V11a6,6,0,0,1,12,0v2H16a1,1,0,0,0-1,1v6a1,1,0,0,0,1,1h3a3,3,0,0,0,3-3V16A3,3,0,0,0,20,13.18ZM7,15v4H5a1,1,0,0,1-1-1V16a1,1,0,0,1,1-1Zm13,3a1,1,0,0,1-1,1H17V15h2a1,1,0,0,1,1,1Z"/></svg> 19 503</span>
						</div>
					</div>

					<div class="release__list">
						<ul class="main__list main__list--playlist main__list--dashbox">
							{% for song in playlist.songs.all %}
							<li class="single-item">
								<a data-playlist data-title="{{ song.name }}" data-artist="{{ song.artist }}" data-img="{{ song.cover_photo.url }}" href="{{ song.audio_file.url }}" class="single-item__cover">
									<img src="{{ song.cover_photo.url }}" alt="">
									<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M18.54,9,8.88,3.46a3.42,3.42,0,0,0-5.13,3V17.58A3.42,3.42,0,0,0,7.17,21a3.43,3.43,0,0,0,1.71-.46L18.54,15a3.42,3.42,0,0,0,0-5.92Zm-1,4.19L7.88,18.81a1.44,1.44,0,0,1-1.42,0,1.42,1.42,0,0,1-.71-1.23V6.42a1.42,1.42,0,0,1,.71-1.23A1.51,1.51,0,0,1,7.17,5a1.54,1.54,0,0,1,.71.19l9.66,5.58a1.42,1.42,0,0,1,0,2.46Z"/></svg>
									<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M16,2a3,3,0,0,0-3,3V19a3,3,0,0,0,6,0V5A3,3,0,0,0,16,2Zm1,17a1,1,0,0,1-2,0V5a1,1,0,0,1,2,0ZM8,2A3,3,0,0,0,5,5V19a3,3,0,0,0,6,0V5A3,3,0,0,0,8,2ZM9,19a1,1,0,0,1-2,0V5A1,1,0,0,1,9,5Z"/></svg>
								</a>
								<div class="single-item__title">
									<h4><a href="#">{{ song.name }}</a></h4>
									<span><a href="artist.html">{{ song.artist }}</a></span>
								</div>
								<a href="#" class="single-item__add">
									<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M19,11H13V5a1,1,0,0,0-2,0v6H5a1,1,0,0,0,0,2h6v6a1,1,0,0,0,2,0V13h6a1,1,0,0,0,0-2Z"/></svg>
								</a>
								<a href="#" class="single-item__export">
									<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M21,14a1,1,0,0,0-1,1v4a1,1,0,0,1-1,1H5a1,1,0,0,1-1-1V15a1,1,0,0,0-2,0v4a3,3,0,0,0,3,3H19a3,3,0,0,0,3-3V15A1,1,0,0,0,21,14Zm-9.71,1.71a1,1,0,0,0,.33.21.94.94,0,0,0,.76,0,1,1,0,0,0,.33-.21l4-4a1,1,0,0,0-1.42-1.42L13,12.59V3a1,1,0,0,0-2,0v9.59l-2.29-2.3a1,1,0,1,0-1.42,1.42Z"></path></svg>
								</a>
							</li>
							{% endfor %}
						</ul>
					</div>
				</div>
			</div>

			<div class="col-12 col-lg-8">
				<div class="article">
					<!-- article content -->
					<div class="article__content">
						<h4>About new playlist</h4>
						<p>{{ playlist.description }}</p>
					</div>
					<!-- end article content -->
				</div>
			</div>
		</div>
	</div>
</main>
<!-- end main content -->
{% endblock %}
	

interactions/templates/interactions/playlists.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
	test
{% endblock %}
{% block content %}
<!-- main content -->
<main class="main">
	<div class="container-fluid">
		<div class="row row--grid">
			<!-- breadcrumb -->
			<div class="col-12">
				<ul class="breadcrumb">
					<li class="breadcrumb__item"><a href="index.html">Home</a></li>
					<li class="breadcrumb__item breadcrumb__item--active">Playlist</li>
				</ul>
			</div>
			<!-- end breadcrumb -->

			<!-- title -->
			<div class="col-12">
				<div class="main__title main__title--page">
					<h1>Playlist</h1>
				</div>
			</div>
			<!-- end title -->
		</div>

		<!-- releases -->
		<div class="row row--grid">
			<div class="col-12">
				<div class="main__filter">
					<form action="#" class="main__filter-search">
						<input type="text" placeholder="Search...">
						<button type="button"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M21.71,20.29,18,16.61A9,9,0,1,0,16.61,18l3.68,3.68a1,1,0,0,0,1.42,0A1,1,0,0,0,21.71,20.29ZM11,18a7,7,0,1,1,7-7A7,7,0,0,1,11,18Z"/></svg></button>
					</form>
				</div>
				<div class="row row--grid">
					{% for playlist in playlists %}
					<div class="col-6 col-sm-4 col-lg-2">
						<div class="album">
							<div class="album__cover">
								<img src="{{ playlist.image.url }}" alt="">
								<a href="{% url 'interactions:playlist' playlist.id %}"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M18.54,9,8.88,3.46a3.42,3.42,0,0,0-5.13,3V17.58A3.42,3.42,0,0,0,7.17,21a3.43,3.43,0,0,0,1.71-.46L18.54,15a3.42,3.42,0,0,0,0-5.92Zm-1,4.19L7.88,18.81a1.44,1.44,0,0,1-1.42,0,1.42,1.42,0,0,1-.71-1.23V6.42a1.42,1.42,0,0,1,.71-1.23A1.51,1.51,0,0,1,7.17,5a1.54,1.54,0,0,1,.71.19l9.66,5.58a1.42,1.42,0,0,1,0,2.46Z"/></svg></a>
								<span class="album__stat">
									<span><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M3.71,16.29a1,1,0,0,0-.33-.21,1,1,0,0,0-.76,0,1,1,0,0,0-.33.21,1,1,0,0,0-.21.33,1,1,0,0,0,.21,1.09,1.15,1.15,0,0,0,.33.21.94.94,0,0,0,.76,0,1.15,1.15,0,0,0,.33-.21,1,1,0,0,0,.21-1.09A1,1,0,0,0,3.71,16.29ZM7,8H21a1,1,0,0,0,0-2H7A1,1,0,0,0,7,8ZM3.71,11.29a1,1,0,0,0-1.09-.21,1.15,1.15,0,0,0-.33.21,1,1,0,0,0-.21.33.94.94,0,0,0,0,.76,1.15,1.15,0,0,0,.21.33,1.15,1.15,0,0,0,.33.21.94.94,0,0,0,.76,0,1.15,1.15,0,0,0,.33-.21,1.15,1.15,0,0,0,.21-.33.94.94,0,0,0,0-.76A1,1,0,0,0,3.71,11.29ZM21,11H7a1,1,0,0,0,0,2H21a1,1,0,0,0,0-2ZM3.71,6.29a1,1,0,0,0-.33-.21,1,1,0,0,0-1.09.21,1.15,1.15,0,0,0-.21.33.94.94,0,0,0,0,.76,1.15,1.15,0,0,0,.21.33,1.15,1.15,0,0,0,.33.21,1,1,0,0,0,1.09-.21,1.15,1.15,0,0,0,.21-.33.94.94,0,0,0,0-.76A1.15,1.15,0,0,0,3.71,6.29ZM21,16H7a1,1,0,0,0,0,2H21a1,1,0,0,0,0-2Z"/></svg> 22</span>
									<span><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M20,13.18V11A8,8,0,0,0,4,11v2.18A3,3,0,0,0,2,16v2a3,3,0,0,0,3,3H8a1,1,0,0,0,1-1V14a1,1,0,0,0-1-1H6V11a6,6,0,0,1,12,0v2H16a1,1,0,0,0-1,1v6a1,1,0,0,0,1,1h3a3,3,0,0,0,3-3V16A3,3,0,0,0,20,13.18ZM7,15v4H5a1,1,0,0,1-1-1V16a1,1,0,0,1,1-1Zm13,3a1,1,0,0,1-1,1H17V15h2a1,1,0,0,1,1,1Z"/></svg> 19 503</span>
								</span>
							</div>
							<div class="album__title">
								<h3><a href="{% url 'interactions:playlist' playlist.pk %}">{{ playlist.name }}</a></h3>
							</div>
						</div>
					</div>
					{% endfor %}
					<div class="col-6 col-sm-4 col-lg-2">
						<div class="album">
							<div class="album__cover">
								<img src="{% static 'img/padd_playlist.png' %}" alt="">
								<a href=""><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M18.54,9,8.88,3.46a3.42,3.42,0,0,0-5.13,3V17.58A3.42,3.42,0,0,0,7.17,21a3.43,3.43,0,0,0,1.71-.46L18.54,15a3.42,3.42,0,0,0,0-5.92Zm-1,4.19L7.88,18.81a1.44,1.44,0,0,1-1.42,0,1.42,1.42,0,0,1-.71-1.23V6.42a1.42,1.42,0,0,1,.71-1.23A1.51,1.51,0,0,1,7.17,5a1.54,1.54,0,0,1,.71.19l9.66,5.58a1.42,1.42,0,0,1,0,2.46Z"/></svg></a>
								<span class="album__stat">
									<span><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M3.71,16.29a1,1,0,0,0-.33-.21,1,1,0,0,0-.76,0,1,1,0,0,0-.33.21,1,1,0,0,0-.21.33,1,1,0,0,0,.21,1.09,1.15,1.15,0,0,0,.33.21.94.94,0,0,0,.76,0,1.15,1.15,0,0,0,.33-.21,1,1,0,0,0,.21-1.09A1,1,0,0,0,3.71,16.29ZM7,8H21a1,1,0,0,0,0-2H7A1,1,0,0,0,7,8ZM3.71,11.29a1,1,0,0,0-1.09-.21,1.15,1.15,0,0,0-.33.21,1,1,0,0,0-.21.33.94.94,0,0,0,0,.76,1.15,1.15,0,0,0,.21.33,1.15,1.15,0,0,0,.33.21.94.94,0,0,0,.76,0,1.15,1.15,0,0,0,.33-.21,1.15,1.15,0,0,0,.21-.33.94.94,0,0,0,0-.76A1,1,0,0,0,3.71,11.29ZM21,11H7a1,1,0,0,0,0,2H21a1,1,0,0,0,0-2ZM3.71,6.29a1,1,0,0,0-.33-.21,1,1,0,0,0-1.09.21,1.15,1.15,0,0,0-.21.33.94.94,0,0,0,0,.76,1.15,1.15,0,0,0,.21.33,1.15,1.15,0,0,0,.33.21,1,1,0,0,0,1.09-.21,1.15,1.15,0,0,0,.21-.33.94.94,0,0,0,0-.76A1.15,1.15,0,0,0,3.71,6.29ZM21,16H7a1,1,0,0,0,0,2H21a1,1,0,0,0,0-2Z"/></svg> 22</span>
									<span><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M20,13.18V11A8,8,0,0,0,4,11v2.18A3,3,0,0,0,2,16v2a3,3,0,0,0,3,3H8a1,1,0,0,0,1-1V14a1,1,0,0,0-1-1H6V11a6,6,0,0,1,12,0v2H16a1,1,0,0,0-1,1v6a1,1,0,0,0,1,1h3a3,3,0,0,0,3-3V16A3,3,0,0,0,20,13.18ZM7,15v4H5a1,1,0,0,1-1-1V16a1,1,0,0,1,1-1Zm13,3a1,1,0,0,1-1,1H17V15h2a1,1,0,0,1,1,1Z"/></svg> 19 503</span>
								</span>
							</div>
							<div class="album__title">
								<h3><a href="">Add playlist</a></h3>
							</div>
						</div>
					</div>
				</div>

			</div>
		</div>
		<!-- end releases -->

	</div>
</main>
<!-- end main content -->

{% endblock %}