config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("songs.urls", namespace="songs")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("interactions/", include("interactions.urls", namespace="interactions")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

songs/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "songs"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("releases/", views.ReleasesView.as_view(), name="releases"),
    path("release/<int:pk>/", views.ReleaseView.as_view(), name="release"),
    path("artists/", views.ArtistsView.as_view(), name="artists"),
    path("artist/<int:pk>/", views.ArtistView.as_view(), name="artist"),
    path("like_unlike/<int:pk>/", views.LikeUnlikeSongView.as_view(), name="like_unlike"),
]

songs/models.py
from django.db import models
# from accounts.models import Band


class Genre(models.Model):
    name = models.CharField(max_length=50)

# Create your models here.
class Song(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    cover_photo = models.ImageField(upload_to="songs/cover_photos", default="default/icon_default.jpg")
    audio_file = models.FileField(upload_to="songs/audio_files")
    band = models.ForeignKey("accounts.Band", on_delete=models.CASCADE, null=True, blank=True)
    artists = models.ManyToManyField("accounts.Artist")
    genres = models.ManyToManyField(Genre)

songs/forms.py
from django import forms


class CommentForm(forms.Form):
    body = forms.CharField(
        widget=forms.TextInput(attrs={
            "id": "text",
            "name": "text",
            "class": "sign__textarea",
            "placeholder": "Add comment",
        }
        )
    )

songs/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.views import View
from .models import Song
from accounts.models import Artist
from .forms import CommentForm
from interactions.models import Comment, Like
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.
class HomeView(View):
    def get(self, request):
        songs = Song.objects.all().order_by("created_at")
        artists = Artist.objects.all().order_by("joined")
        song = songs.last()
        context = {"songs": songs, "song": song, "artists": artists}
        return render(request, "songs/index.html", context=context)


class ReleasesView(View):
    def get(self, request, *args, **kwargs):
        songs = Song.objects.all().order_by("created_at")
        context = {"songs": songs}
        return render(request, "songs/releases.html", context=context)


class ReleaseView(View):
    form_class = CommentForm

    def get(self, request, *args, **kwargs):
        song = Song.objects.get(pk=kwargs["pk"])
        user = request.user
        liked = Like.objects.filter(user=user, song=song).exists()
        number_of_likes = song.like_set.all().count()
        form = self.form_class
        context = {"song": song, "form": form, "liked": liked, "number_of_likes": number_of_likes}
        return render(request, "songs/release.html", context=context)

    def post(self, request, *args, **kwargs):
        if "submit_new" in request.POST:
            form = self.form_class(request.POST)
            if form.is_valid():
                cd = form.cleaned_data
                body = cd["body"]
                user = request.user
                song = Song.objects.get(pk=kwargs["pk"])
                Comment.objects.create(body=body, user=user, song=song)
                return redirect("songs:release", song.pk)

        if "submit_reply" in request.POST:
            form = self.form_class(request.POST)
            if form.is_valid():
                cd = form.cleaned_data
                body = cd["body"]
                comment_id = request.POST.get("comment_id")
                parent_comment = Comment.objects.get(pk=comment_id)
                user = request.user
                song = Song.objects.get(pk=kwargs["pk"])
                Comment.objects.create(
                    body=body,
                    user=user,
                    song=song,
                    comment_reply=parent_comment,
                    is_reply=True,
                )
                return redirect("songs:release", song.pk)


class ArtistsView(View):
    def get(self, request, *args, **kwargs):
        artists = Artist.objects.all().order_by("joined")
        context = {"artists": artists}
        return render(request, "songs/artists.html", context=context)


class ArtistView(View):
    def get(self, request, *args, **kwargs):
        artist = Artist.objects.get(pk=kwargs["pk"])
        context = {"artist": artist}
        return render(request, "songs/artist.html", context=context)


class LikeUnlikeSongView(LoginRequiredMixin, View):
    def setup(self, request, *args, **kwargs):
        super().setup(request, *args, **kwargs)
        self.user = request.user
        self.song = Song.objects.get(pk=kwargs["pk"])
        self.liked = Like.objects.filter(user=self.user, song=self.song).exists()
    
    def post(self, request, *args, **kwargs):
        is_ajax = request.headers.get('X-Requested-With') == 'XMLHttpRequest'
        if is_ajax:          
            if self.liked:
                Like.objects.filter(user=self.user, song=self.song).delete()
            else:
                Like.objects.create(user=self.user, song=self.song)
            number_of_likes = self.song.like_set.all().count()
            liked = Like.objects.filter(user=self.user, song=self.song).exists()
            data = {'number_of_likes': number_of_likes, 'liked':liked, "message": "successful"}
            return JsonResponse(data)

songs/templates/songs/artist.html
<!-- main content -->
{% extends 'base.html' %}
{% load static %}
{% block title %}
	test
{% endblock %}
{% block content %}
<main class="main">
	<div class="container-fluid">
		<div class="row row--grid">
			<div class="col-12">
				<div class="article article--page">
					<!-- article content -->
					<div class="article__content">
						<div class="article__artist">
							<img src="img/artists/artist1.jpg" alt="">
							<div>
								<h1>{{ artist.name }}</h1>
								<span>John Doe</span>
								<p>{{ artist.description }}</p>
							</div>
						</div>

					</div>
					<!-- end article content -->
				</div>
			</div>
		</div>

		<!-- releases -->
		<section class="row row--grid">
			<!-- title -->
			<div class="col-12">
				<div class="main__title">
					<h2>Releases</h2>
				</div>
			</div>
			<!-- end title -->
			{% for song in artist.song_set.all %}
			<div class="col-6 col-sm-4 col-lg-2">
				<div class="album">
					<div class="album__cover">
						<img src="{{ song.cover_photo.url }}" alt="">
						<a href="{% url 'songs:release' song.pk %}"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M18.54,9,8.88,3.46a3.42,3.42,0,0,0-5.13,3V17.58A3.42,3.42,0,0,0,7.17,21a3.43,3.43,0,0,0,1.71-.46L18.54,15a3.42,3.42,0,0,0,0-5.92Zm-1,4.19L7.88,18.81a1.44,1.44,0,0,1-1.42,0,1.42,1.42,0,0,1-.71-1.23V6.42a1.42,1.42,0,0,1,.71-1.23A1.51,1.51,0,0,1,7.17,5a1.54,1.54,0,0,1,.71.19l9.66,5.58a1.42,1.42,0,0,1,0,2.46Z"/></svg></a>
						<span class="album__stat">
							<span><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M3.71,16.29a1,1,0,0,0-.33-.21,1,1,0,0,0-.76,0,1,1,0,0,0-.33.21,1,1,0,0,0-.21.33,1,1,0,0,0,.21,1.09,1.15,1.15,0,0,0,.33.21.94.94,0,0,0,.76,0,1.15,1.15,0,0,0,.33-.21,1,1,0,0,0,.21-1.09A1,1,0,0,0,3.71,16.29ZM7,8H21a1,1,0,0,0,0-2H7A1,1,0,0,0,7,8ZM3.71,11.29a1,1,0,0,0-1.09-.21,1.15,1.15,0,0,0-.33.21,1,1,0,0,0-.21.33.94.94,0,0,0,0,.76,1.15,1.15,0,0,0,.21.33,1.15,1.15,0,0,0,.33.21.94.94,0,0,0,.76,0,1.15,1.15,0,0,0,.33-.21,1.15,1.15,0,0,0,.21-.33.94.94,0,0,0,0-.76A1,1,0,0,0,3.71,11.29ZM21,11H7a1,1,0,0,0,0,2H21a1,1,0,0,0,0-2ZM3.71,6.29a1,1,0,0,0-.33-.21,1,1,0,0,0-1.09.21,1.15,1.15,0,0,0-.21.33.94.94,0,0,0,0,.76,1.15,1.15,0,0,0,.21.33,1.15,1.15,0,0,0,.33.21,1,1,0,0,0,1.09-.21,1.15,1.15,0,0,0,.21-.33.94.94,0,0,0,0-.76A1.15,1.15,0,0,0,3.71,6.29ZM21,16H7a1,1,0,0,0,0,2H21a1,1,0,0,0,0-2Z"/></svg> 22</span>
							<span><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M20,13.18V11A8,8,0,0,0,4,11v2.18A3,3,0,0,0,2,16v2a3,3,0,0,0,3,3H8a1,1,0,0,0,1-1V14a1,1,0,0,0-1-1H6V11a6,6,0,0,1,12,0v2H16a1,1,0,0,0-1,1v6a1,1,0,0,0,1,1h3a3,3,0,0,0,3-3V16A3,3,0,0,0,20,13.18ZM7,15v4H5a1,1,0,0,1-1-1V16a1,1,0,0,1,1-1Zm13,3a1,1,0,0,1-1,1H17V15h2a1,1,0,0,1,1,1Z"/></svg> 19 503</span>
						</span>
					</div>
					<div class="album__title">
						<h3><a href="{% url 'songs:release' song.pk %}">{{ song.name }}</a></h3>
						{% for artist in song.artists.all%}
						<span>
							<a href="{% url 'songs:artist' artist.pk %}">{{ artist }}</a>{% if not forloop.last %} & {% endif %}
						</span>
						{% endfor %}
					</div>
				</div>
			</div>
			{% endfor %}

		</section>
		<!-- end releases -->

	</div>
</main>
{% endblock %}
<!-- end main content -->


songs/templates/songs/artists.html
<!-- main content -->
{% extends 'base.html' %}
{% load static %}
{% block title %}
	test
{% endblock %}
{% block content %}
<main class="main">
	<div class="container-fluid">
		<!-- artists -->
		<div class="row row--grid">
			<!-- breadcrumb -->
			<div class="col-12">
				<ul class="breadcrumb">
					<li class="breadcrumb__item"><a href="{% url 'songs:home' %}">Home</a></li>
					<li class="breadcrumb__item breadcrumb__item--active">Artists</li>
				</ul>
			</div>
			<!-- end breadcrumb -->

			<!-- title -->
			<div class="col-12">
				<div class="main__title main__title--page">
					<h1>Artists</h1>
				</div>
			</div>
			<!-- end title -->
		</div>

		<div class="row row--grid">
			<div class="col-12">
				<div class="main__filter">
					<form action="#" class="main__filter-search">
						<input type="text" placeholder="Search...">
						<button type="button"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M21.71,20.29,18,16.61A9,9,0,1,0,16.61,18l3.68,3.68a1,1,0,0,0,1.42,0A1,1,0,0,0,21.71,20.29ZM11,18a7,7,0,1,1,7-7A7,7,0,0,1,11,18Z"/></svg></button>
					</form>

					<div class="main__filter-wrap">
						<select class="main__select" name="genres">
							<option value="all">All artists</option>
							<option value="legacy">Legacy artists</option>
							<option value="active">Active artists</option>
						</select>

						<select class="main__select" name="years">
							<option value="All genres">All genres</option>
							<option value="1">Alternative</option>
							<option value="2">Blues</option>
							<option value="3">Classical</option>
							<option value="4">Country</option>
							<option value="5">Electronic</option>
							<option value="6">Hip-Hop/Rap</option>
							<option value="7">Indie</option>
							<option value="8">Jazz</option>
							<option value="8">Latino</option>
							<option value="8">R&B/Soul</option>
							<option value="8">Rock</option>
						</select>
					</div>

					<div class="slider-radio">
						<input type="radio" name="grade" id="featured" checked="checked"><label for="featured">Featured</label>
						<input type="radio" name="grade" id="popular"><label for="popular">Popular</label>
						<input type="radio" name="grade" id="newest"><label for="newest">Newest</label>
					</div>
				</div>

				<div class="row row--grid">
					{% for artist in artists %}
					<div class="col-6 col-sm-4 col-md-3 col-xl-2">
						<a href="{% url 'songs:artist' artist.pk %}" class="artist">
							<div class="artist__cover">
								<img src="{{ artist.image.url }}" alt="">
							</div>
							<h3 class="artist__title">{{ artist.name }}</h3>
						</a>
					</div>
					{% endfor %}
				</div>

				<button class="main__load" type="button">Load more</button>
			</div>
		</div>
		<!-- end artists -->
	</div>
</main>
{% endblock %}
<!-- end main content -->


songs/templates/songs/releases.html
<!-- main content -->
{% extends 'base.html' %}
{% load static %}
{% block title %}
	test
{% endblock %}
{% block content %}
<main class="main">
	<div class="container-fluid">
		<div class="row row--grid">
			<!-- breadcrumb -->
			<div class="col-12">
				<ul class="breadcrumb">
					<li class="breadcrumb__item"><a href="{% url 'songs:home' %}">Home</a></li>
					<li class="breadcrumb__item breadcrumb__item--active">Releases</li>
				</ul>
			</div>
			<!-- end breadcrumb -->

			<!-- title -->
			<div class="col-12">
				<div class="main__title main__title--page">
					<h1>Releases</h1>
				</div>
			</div>
			<!-- end title -->
		</div>

		<!-- releases -->
		<div class="row row--grid">
			<div class="col-12">
				<div class="main__filter">
					<form action="#" class="main__filter-search">
						<input type="text" placeholder="Search...">
						<button type="button"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M21.71,20.29,18,16.61A9,9,0,1,0,16.61,18l3.68,3.68a1,1,0,0,0,1.42,0A1,1,0,0,0,21.71,20.29ZM11,18a7,7,0,1,1,7-7A7,7,0,0,1,11,18Z"/></svg></button>
					</form>
				</div>

				<div class="row row--grid">
					{% for song in songs %}
					<div class="col-6 col-sm-4 col-lg-2">
						<div class="album">
							<div class="album__cover">
								<img src="{{ song.cover_photo.url }}" alt="">
								<a href="{% url 'songs:release' song.pk %}"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M18.54,9,8.88,3.46a3.42,3.42,0,0,0-5.13,3V17.58A3.42,3.42,0,0,0,7.17,21a3.43,3.43,0,0,0,1.71-.46L18.54,15a3.42,3.42,0,0,0,0-5.92Zm-1,4.19L7.88,18.81a1.44,1.44,0,0,1-1.42,0,1.42,1.42,0,0,1-.71-1.23V6.42a1.42,1.42,0,0,1,.71-1.23A1.51,1.51,0,0,1,7.17,5a1.54,1.54,0,0,1,.71.19l9.66,5.58a1.42,1.42,0,0,1,0,2.46Z"/></svg></a>
								<span class="album__stat">
									<span><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M3.71,16.29a1,1,0,0,0-.33-.21,1,1,0,0,0-.76,0,1,1,0,0,0-.33.21,1,1,0,0,0-.21.33,1,1,0,0,0,.21,1.09,1.15,1.15,0,0,0,.33.21.94.94,0,0,0,.76,0,1.15,1.15,0,0,0,.33-.21,1,1,0,0,0,.21-1.09A1,1,0,0,0,3.71,16.29ZM7,8H21a1,1,0,0,0,0-2H7A1,1,0,0,0,7,8ZM3.71,11.29a1,1,0,0,0-1.09-.21,1.15,1.15,0,0,0-.33.21,1,1,0,0,0-.21.33.94.94,0,0,0,0,.76,1.15,1.15,0,0,0,.21.33,1.15,1.15,0,0,0,.33.21.94.94,0,0,0,.76,0,1.15,1.15,0,0,0,.33-.21,1.15,1.15,0,0,0,.21-.33.94.94,0,0,0,0-.76A1,1,0,0,0,3.71,11.29ZM21,11H7a1,1,0,0,0,0,2H21a1,1,0,0,0,0-2ZM3.71,6.29a1,1,0,0,0-.33-.21,1,1,0,0,0-1.09.21,1.15,1.15,0,0,0-.21.33.94.94,0,0,0,0,.76,1.15,1.15,0,0,0,.21.33,1.15,1.15,0,0,0,.33.21,1,1,0,0,0,1.09-.21,1.15,1.15,0,0,0,.21-.33.94.94,0,0,0,0-.76A1.15,1.15,0,0,0,3.71,6.29ZM21,16H7a1,1,0,0,0,0,2H21a1,1,0,0,0,0-2Z"/></svg> 22</span>
									<span><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M20,13.18V11A8,8,0,0,0,4,11v2.18A3,3,0,0,0,2,16v2a3,3,0,0,0,3,3H8a1,1,0,0,0,1-1V14a1,1,0,0,0-1-1H6V11a6,6,0,0,1,12,0v2H16a1,1,0,0,0-1,1v6a1,1,0,0,0,1,1h3a3,3,0,0,0,3-3V16A3,3,0,0,0,20,13.18ZM7,15v4H5a1,1,0,0,1-1-1V16a1,1,0,0,1,1-1Zm13,3a1,1,0,0,1-1,1H17V15h2a1,1,0,0,1,1,1Z"/></svg> 19 503</span>
								</span>
							</div>
							<div class="album__title">
								<h3><a href="{% url 'songs:release' song.pk %}">{{ song.name }}</a></h3>
								<span>
									{% for artist in song.artists.all %}
									<a href="{% url 'songs:artist' artist.pk %}">{{ artist.name }}</a> {% if not forloop.last %}&{% endif %}
									{% endfor %}
								</span>
							</div>
						</div>
					</div>
					{% endfor %}
				</div>
			</div>
		</div>
		<!-- end releases -->	
	</div>
</main>
{% endblock %}
<!-- end main content -->